CFLAGS = -g -O2 -Wall -Werror -Wno-unused
	* C compile flag

CFLAGS = -I/usr/include
	* specify the path to header files

CXXFLAGS
	* C++ compile flag

LDFLAS = -L/usr/lib
	* tell linker where to find lib

LIBS = -lpthread
	* tell linker which lib to link
