CFLAGS = -g -O2 -Wall -Werror -Wno-unused
	* C compile flag

CFLAGS = -I/usr/include
	* specify the path to header files

CXXFLAGS
	* C++ compile flag

LDFLAS = -L/usr/lib
	* tell linker where to find lib

LIBS = -lpthread
	* tell linker which lib to link

echo_test:
	echo "hello1"
	@echo "hello2"
	# `echo hello1` will also show on terminal

STRING = 'this is a string'
	* define a string

x = foo
y= $(x) bar
x = xyz
# y will be `xyz bar`, because
