# Description

# Overview
* Written in Python

* to generate build.ninja file for ninja to build
    * build.ninja is like Makefile
    * still require ninja to compile

* pip3 install meson
    * meson installed by pip has higher version than installed by apt
    * path /usr/local/bin/meson
* meson installed by apt will be in /usr/bin/meson
    * if we remove apt meson and install pip3 meson, we need to run `hash -d meson` to flush shell cache

* a typical usage
    $ mkdir build
    $ meson setup build
    $ cd build && ninja
        * or $ ninja -C build
    * after ninja building, if we change source code, we can just run ninja again and it will auto run meson if needed.

* files
    * meson.build
        * the main build definition file for meson
        * in source root and subdirectories
    * meson_options.txt
        * declares build options that user can configure
        * optional file in the source root
    * build/build.ninja
        * the low-level build script generated by meson for ninja to execute
        * like Makefile for make
        * don't edit this file by hand
    * build/compile_commands.json
        * generated by meson
        * contains a JSON array of compile commands for each source file
        * mostly used by language servers by IDE
    * build/meson-info/*
        * stores meson configuration data

* meson.build
    * include_directories
        ```
        inc_log = include_directories(
            'inc',
            'log/inc',
        )
        ```
        * 

# Options

# Example
$ meson build --prefix=$PWD/install/
    * like "make configure"
    * create build/ and generate configuration files for compilation
    * --prefix=path/to/install specifies the dir to place to install binaries
    * we can check the configuration again in build/meson-logs/

$ meson build/ --reconfigure --prefix=/opt/install/
$ meson configure build --prefix=/opt/install/
    * configure again

$ meson configure build/
    * show current options in build/, useful to check --prefix value

$ meson build/ --buildtype debug --reconfigure
    * reconfigure with debug symbols
    * buildtype:
        * plain: no extra build flags
        * debug: with debug symbol, no optimization
        * debugoptimized: with debug symbol and optimization
        * release: with optimization, no debug symbol

$ meson build -Dc_args=... -Dcpp_args=... -Dc_link_args=... -Dcpp_link_args=...
    * add gcc flags

$ meson test -C build/
    * run unit tests when they are avaliable

$ DESTDIR=$PWD/install meson install -C build/
    * setup prefix if forgetting it before

$ ninja -C build/ -j`nproc`
    * like "make"
    * -C <dir> means change to <dir> before doing anything else

$ ninja -C build/ install
    * like "make install"
    * build and install binaries to specified place

$ ninja -C build/ clean
    * like "make clean"
