# Description

# Overview
* also check man page of
    * trace-cmd-record

* check what events, functions are supported
    /sys/kernel/tracing/available_events
    /sys/kernel/tracing/available_filter_functions_addrs
    /sys/kernel/tracing/available_filter_functions
    /sys/kernel/tracing/available_tracers

* ref
    * https://blog.csdn.net/zmjames2000/article/details/88410484
    * https://blog.csdn.net/weixin_44410537/article/details/103587609

# Options
-e amdgpu:*
    * trace all AMDGPU driver events
    * need tracepoint in /sys/kernel/tracing/available_events

-p function -l amdgpu_job_submit --func-stack
    * -p function specifies the filter to use
    * -l traces a specific C function (limit), disregarding its children
        * need function in /sys/kernel/tracing/available_filter_functions
    * --func-stack records stacktrace when functions are hit

-p function_graph -g amdgpu_gem_create_ioctl -n amdgpu_job_submit
    * use graph tracer and start graphing when amdgpu_gem_create_ioctl is hit
    * and stop when amdgpu_jobsubmit is hit (optional)
    * overhead is high since every single function call during it will be recorded

-e amdgpu:amdgpu_bo_create --trigger stacktrace
    * check the callstack to this event
    * tracing event is more powerful since it can show the parameter

-F ./app
    * run the command and only trace events generated by it

sleep 5
    * capture system-wide activity for 5 sec

# Example
$ sudo trace-cmd list -e | grep "drm\|amdgpu"
    * show available tracepoints (events)
    	* from /sys/kernel/tracing/available_events
    * drm
        - drm:drm_ioctl_entry: when kernel receives any ioctl
        - drm:drm_ioctl_exit: when ioctl finished
        - drm:drm_open: when calling open("/dev/dri/...")
    * amdgpu
        - amdgpu:amdgpu_bo_create: when allocaing memory in VRAM or GTT
        - amdgpu:amdgpu_bo_move: when driver moves buffer from GTT to VRAM or vice versa
        - amdgpu:amdgpu_vm_bo_map: when a buffer is mapping into GPU VA space
        - amdgpu:amdgpu_cs_ioctl: when app submits a command buffer
        - amdgpu:amdgpu_sched_run_job: when the drm scheduler actually picks up a job to run


$ trace-cmd convert -i trace-7.dat -o trace-6.dat --file-version 6
    * covert trace log format to version 6

$ sudo trace-cmd record --file-version 6 -e amdgpu_sched_run_job -l amdgpu_job_submit -l <first_caller_in_stack> -p function --func-stack sleep 5
$ sudo trace-cmd record --file-version 6 -e amdgpu_sched_run_job -l amdgpu_job_submit -l amdgpu_vm_sdma_commit -p function --func-stack sleep 5
$ sudo trace-cmd report trace.dat

$ sudo trace-cmd record --file-version 6 \
  -e "amdgpu:amdgpu_cs_ioctl" \
  -e "amdgpu:amdgpu_sched_run_job" \
  -e "*fence:*fence_signaled" \
  -e "drm:drm_vblank_event"

$ sudo trace-cmd stream -p function -l amdgpu_dm_atomic_check --func-stack sleep 2
    * steam means directly output to stdout
    * -p function means trace function
    * -l specifies the function
    * --func-stack prints the callstack

$ sudo trace-cmd stream -e amdgpu_dm:amdgpu_dm_atomic_commit_tail_begin -l amdgpu_dm_atomic_commit_tail

$ sudo trace-cmd stream -e amdgpu:amdgpu_cs_ioctl sleep 3
$ sudo trace-cmd record --file-version 6 -e amdgpu:amdgpu_sched_run_job sleep 3

$ trace-cmd record -p function_graph -g 'amdgpu_dm_atomic_commit_tail' -g 'dm_hw_init' --module 'amdgpu'
$ trace-cmd report trace.dat
$ trace-cmd report --profile trace.dat
    * -p function_graph can check time spent in a function

$ trace-cmd record \
    -e amdgpu:amdgpu_bo_create -f "size > 1024" \
    -F ./app
    * check the filed names of amdgpu_bo_create, see `size`
        $ cat /sys/kernel/tracing/events/amdgpu/amdgpu_bo_create/format
    * only record if the buffer size is greater than 1024 bytes
